#!/bin/bash

# Wrapper script to execute the rest of the build.
# Don't run directly. Meson will exec this for you.

# DO NOT modify the argument order.

PROJECT_NAME=$1
KERNEL_FILE=$2

IMG_NAME=${PROJECT_NAME}.img

MESON_BUILD_DIR=${MESON_BUILD_ROOT}
MESON_SOURCE_DIR=${MESON_SOURCE_ROOT}

MESON_MOUNT_DIR=/mnt/loop/${PROJECT_NAME}
MESON_IMG=${MESON_BUILD_DIR}/${IMG_NAME}
MESON_KERNEL=${MESON_BUILD_DIR}/${KERNEL_NAME}

if [[ ! -f ${MESON_BUILD_DIR}/${IMG_NAME} ]]; then
    touch ${MESON_BUILD_DIR}/${IMG_NAME}
fi

echo $1 $2 $3 ${MESON_BUILD_DIR} ${MESON_SOURCE_DIR} ${MESON_MOUNT_DIR} ${MESON_IMG} ${MESON_KERNEL}

# DO NOT modify the execution order.

# do_parts.sh MESON_BUILD_DIR MESON_IMG
# do_echfs.sh MESON_BUILD_DIR MESON_SOURCE_DIR MESON_IMG
# do_imports.sh MESON_BUILD_DIR MESON_SOURCE_DIR MESON_IMG MESON_KERNEL
# do_losetup.sh MESON_BUILD_DIR MESON_IMG MESON_MOUNT_DIR
# do_efi.sh MESON_BUILD_DIR MESON_SOURCE_DIR MESON_IMG MESON_MOUNT_DIR
# do_clean.sh MESON_SOURCE_DIR MESON_IMG MESON_MOUNT_DIR